[package]
name = "lava_torrent"
version = "0.3.0"
authors = ["ttlajus <40629580+ttlajus@users.noreply.github.com>"]
description = "A library for parsing/encoding bencode and .torrent files."
repository = "https://github.com/ttlajus/lava_torrent"
readme = "README.md"
keywords = ["bittorrent", "bencode"]
categories = ["parsing", "encoding"]
license = "MIT OR Apache-2.0"

[badges]
travis-ci = { repository = "ttlajus/lava_torrent" }
codecov = { repository = "ttlajus/lava_torrent" }

[dependencies]
itertools = "0.7.7"
unicode-normalization = "0.1.5"
conv = "0.3.3"
rust-crypto = "0.2.36"
error-chain = "0.12.0"

[dev-dependencies]
rand = "0.5.5"
